### ISSUE TITLE
Feature request: allow user configurable number of old kernels to retain

### ISSUE THREAD

**Issue by terackspace** [rackerlabs/kthresher#6]
We would like to implement a control in /etc/default/kthresher that allows the user to specify how many kernels older than the currently running one will be kept. This will allow the local systems admin to decide if they wish to retain "fallback" kernels for emergency boot problems (i.e. if rebuilding an initrd/initramfs fails to boot, provide a fallback kernel). Something like:

```
/etc/default/kthresher
----------------------
NUMTOKEEP=1
```

This is just a sketch of design of the intended spirit.

**Comment by tonyskapunk** [comment]
Did some on research to find what would be the best place for a configuration file, turns out `/etc/default/` is mainly used for `crons` and _sysV/upstart_ config files[1][2].  I'm thinking in using `/etc/kthresher.conf` for this _if we need to_,  going to add a command line option to support this initially.

[1] https://www.debian.org/doc/debian-policy/ch-files.html#s-config-files
[2] http://0pointer.de/blog/projects/on-etc-sysinit.html

**Comment by tonyskapunk** [comment]
At this point there is support to keep a `N` number(up to 9) of kernel images.  If the intent is to use a cronjob(as noted in #5 ) to execute `kthresher` I can't see the advantage of having a configuration file for it, do we have any use case that this will benefit or improve the use of `kthresher`?

**Comment by tonyskapunk** [comment]
Talked to @terackspace  about this, it makes sense to have a config file for this, will start working on this.

**Comment by tonyskapunk** [comment]
@terackspace now we have a `kthresher` that supports `keep` and `config` options, being `/etc/kthresher.conf` the default config file.  I provide a default config file [kthresher.conf.example](https://github.com/rackerlabs/kthresher/blob/master/docs/kthresher.conf.example) that can be used to place it under `/etc/kthresher.conf`, this should cover this feature request.

**Comment by tonyskapunk** [comment]
Closing this as is now implemented
