### ISSUE TITLE
cron job should not fail if the binary does not exist

### ISSUE THREAD

**Issue by jkirk** [rackerlabs/kthresher#62]
It has been reported that the cronjob exits with an error if the binary has been removed.

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919247

**Comment by tonyskapunk** [comment]
@jkirk for packaging matters, do you have a preference to move this and the other bug into `master`?

That is make a new release (e.g. `1.3.1`) with those two patches (this one and [the other bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919457), fixed in #59) or are you ok if I release these as part of `1.4.0` ?

**Comment by jkirk** [comment]
@tonyskapunk I think we should directly go for `1.4.0`

**Comment by tonyskapunk** [comment]
Sounds good, I plan to release it next week, thanks!!
